dist:
  module: github.com/git-ecosystem/sample-trace2-otel-collector
  name: sample-trace2-otel-collector
  description: Custom OTEL Collector to convert and relay Git Trace2 data to OTLP
  otelcol_version: 0.112.0
  output_path: .
  version: 0.0.0

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/azuremonitorexporter v0.112.0
  - import: go.opentelemetry.io/collector/exporter/debugexporter
    gomod: go.opentelemetry.io/collector v0.112.0
  - import: go.opentelemetry.io/collector/exporter/otlpexporter
    gomod: go.opentelemetry.io/collector v0.112.0

receivers:
  - gomod: github.com/git-ecosystem/trace2receiver v0.5.6

processors:
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.112.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.17.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.17.0
